apiVersion: v2
name: nova-pollinate
description: A Helm chart for Nova Pollinate
type: application
version: 1.0.8
appVersion: 0.1-2-g03fecd4
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
