apiVersion: v2
name: nova-pollinate
description: A Helm chart for Nova Pollinate
type: application
version: 1.4.5
appVersion: 0.2.4
dependencies:
- name: nectarlib
  version: 4.2.0
  repository: oci://registry.rc.nectar.org.au/nectar-helm
