apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nova-pollinate.fullname" . }}
data:
  IMAGE_ID: "{{ .Values.image.tag | default .Chart.AppVersion }}"
{{- range $key, $val := .Values.conf }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
