---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nova-pollinate.fullname" . }}
  labels:
    {{- include "nova-pollinate.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nova-pollinate.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - {}
  ingress:
    - ports:
        - port: 8080
