apiVersion: v1
kind: Service
metadata:
  name: {{ include "nova-pollinate.fullname" . }}
  labels:
    {{- include "nova-pollinate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "nova-pollinate.selectorLabels" . | nindent 4 }}
